### ISSUE TITLE
User restrictions

### ISSUE THREAD

**Issue by jcrist** [jcrist/dask-gateway#25]
From an admin perspective it may sometimes be useful to support restrictions on user resource usage. A few examples:

- Maximum number of workers per user
- Maximum resources per user
- Maximum number of clusters per user

We should probably provide a common metrics, but will likely also need a generic hook for operations an admin may want to restrict. This may look like:

```python
def can_start_cluster(user):
    """Check if a user can start a cluster.
    
    Returns
    -------
    allowed : bool
        True if the user can start a cluster, False otherwise
    msg : str or None
        A user-facing message explaining why the operation is currently forbidden.
    """
    pass

def can_start_worker(user, cluster):
    """Check if a user can start a worker.
    
    Returns
    -------
    allowed : bool
        True if the user can start a worker, False otherwise
    msg : str or None
        A user-facing message explaining why the operation is currently forbidden.
    """
    pass
```

**Comment by jcrist** [comment]
cc @jhamman, this is related to our discussion earlier.

**Comment by jcrist** [comment]
I'm looking at adding this. A few limits we may want to support out of the box:

- Max clusters per user
- Max {workers, cores, memory} per cluster
- Max memory/cores per user?

The last one I'm not sure if it's worth supporting. I can think of two ways a restriction model could be implemented:

1. Limits with clusters as the fundamental unit, and then limits internal to each cluster (workers, memory, cores). This is easy to reason about (I can have up to 5 clusters, each with up to 10 cores), and easy to implement. Downside is that what admins usually care about is resource usage, not the abstractions built on top. You can still restrict users to maximum limits, but you'd also dictate how they'd have to break that up (e.g. a limit of 5 clusters of 10 cores each wouldn't allow 1 cluster with 100 cores). This would expose:

  - Max clusters per user
  - Max workers per cluster
  - Max memory per cluster
  - Max cores per cluster

2. Limits with resources (memory, cores) as the fundamental unit. This is a bit more complicated to reason about and implement, but gets more at what admins usually care about. This would expose:

  - Max memory per user
  - Max cores per user
  - Max clusters per user
  - Max workers per cluster?
  - Max memory per cluster?
  - Max cores per cluster?

I'm also unsure if a flat restriction model is enough, or if we'd want limits specific to each user (e.g. user `alice` gets more resources than user `ben`).

**Comment by jcrist** [comment]
Also, if a user hits a resource limit, what should happen? A few scenarios:

- User tries to create a new cluster, but the restrictions prevent this. I think this should error. The other option would be to hang until available, but this would be much trickier to implement.

- User calls `cluster.scale(50)`, but this exceeds some resource/worker restriction. 3 options:
  - We could error informatively. This may make sense if the users code relies on that many workers, and we know we'd never get them to them.
  - We could warn, and scale to the maximum allowed size. Downside is in automated settings warnings aren't always seen, and could instead lead to a slower script or a failure at a later point.
  - If the limit could potentially resolve (e.g. they request 100 cores, have a user max of 120 cores, but 50 of them are currently on another cluster that eventually scales down), we could put these workers in pending, and schedule them later when resources are available. This would be much more complicated to implement, and moves some of what the backing resource-manager (e.g. YARN) should be doing into dask-gateway itself. Still, some backends don't have resource queues and this could be useful in certain contexts.

Right now I'm leaning towards erroring when trying to start a cluster would exceed a restriction, and either erroring or warning when trying to exceed some worker restrictions.

**Comment by jcrist** [comment]
See also https://github.com/dask/distributed/issues/3054

**Comment by ericdill** [comment]
Enterprise orgs typically think in groups of users, not individual users. For example, we've regularly heard from our customers that they want to be able to restrict the different resource profiles on Anaconda Enterprise to different groups citing that they'd want their Data Science team to have access to the really big resource profiles while their less sophisticated Business Intelligence folks wouldn't need, for example, a 4GPU resource profile. Not sure how that impacts what you're looking to do here.

**Comment by martindurant** [comment]
This is a massive improvement in the usefulness of Gateway, wholly in favour! I can perhaps help.
I agree with erring for situation 1. . For 2. it is indeed tricky, I think I favour an error still ("please try again later"!), but obviously autoscaling needs to know that scaling can fail.

To @ericdill 's comment: `can_start_worker`, etc., would be pluggable, and the org can implement how they make this decision themselves?

**Comment by jcrist** [comment]
> Enterprise orgs typically think in groups of users, not individual users.

We don't currently support groups in our user model, although this is something we could do. I agree that group-level restriction sets would be what we'd want if we supported anything other than uniform restrictions.

**Comment by ericdill** [comment]
> User calls cluster.scale(50), but this exceeds some resource/worker restriction. 3 options:

I like option 2. When libraries/frameworks/apps do what you suggest in option 1, it always feels a bit pedantic. "Look, I need lots of workers why are you making me specify that I can only ask for 49 instead of 50" can be a really annoying UX

**Comment by ericdill** [comment]
> I agree that group-level restriction sets would be what we'd want if we supported anything other than uniform restrictions.

As long we don't engineer ourselves into a corner with respect to this at some point in the future, I'd suggest punting on it for now

**Comment by ericdill** [comment]
ohh i think i misunderstood this whole issue. You're talking about having one restriction rule (for each resource category) for _all_ users

**Comment by jcrist** [comment]
I have WIP of this in #93.
