### ISSUE TITLE
Helm Chart for kubernetes deployment

### ISSUE THREAD

**Issue by jcrist** [jcrist/dask-gateway#44]
As of #43 we support kubernetes as a backend. It would be good to develop a helm chart for deploying this on kubernetes clusters. I have no helm experience, but may eventually be able to figure this out - others will likely have an easier time at it. Here's a high level of how I see a kubernetes deployment looking:

- The gateway will have three components running and managed by a deployment:
  
  - The gateway process (`dask-gateway-server`)
  - The scheduler proxy (`dask-gateway-server scheduler-proxy`)
  - The web proxy (`dask-gateway-server web-proxy`)

  The resources for these are all part of the `dask-gateway-server` python package, and could all be run using the same image (but in different containers). I think we'd want different containers rather than running in the same container to let kubernetes handle restarts (the gateway should be robust to transient component restarts). The appropriate configuration would need to be set to allow for this (this exists, but is only documented at the traitlets config level).

- We'd want to expose configuration for common things via helm. We should be able to do this similar to the way jupyterhub does (https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/images/hub/jupyterhub_config.py). A few things people may be interested in:

  - All the configurable traitlets on `dask_gateway_server.managers.kubernetes.KubeClusterManager`
  - The authenticator used
  - The database url
  - Various timeouts

- I'm not sure how people would run this with a persistent database in kubernetes. A few ideas:

  - In memory database only, not robust to gateway restarts (this should maybe be the default)
  - Sqlite stored on a PVC
  - Some custom db url (the user would be responsible for setting up the db externally)

- We should provide default images to use. One already exists for running the scheduler/worker processes [here](https://github.com/jcrist/dask-gateway/tree/master/resources/docker/dask-gateway). All deployment resources should go somewhere under [this directory](https://github.com/jcrist/dask-gateway/tree/master/resources).

- It would be good to have a way to demo this locally on minikube. We have a demo for a hadoop cluster [here](https://github.com/jcrist/dask-gateway/tree/master/demo), it would be nice to replicate this for kubernetes.

**Comment by jcrist** [comment]
cc @mrocklin, you were asking about this.

**Comment by jcrist** [comment]
We should also support (optional) RBAC role configuration. The `gateway` container would be the only one in need of a service account. As currently written it's satisfied by the following configuration:
https://github.com/jcrist/dask-gateway/blob/517dc5938a10356b06843893f9ac7fe0deed4c2f/continuous_integration/kubernetes/start.sh#L55-L83.

**Comment by mrocklin** [comment]
cc @beberg @supertetelman @miroenev

cc @jacobtomlinson @quasiben (after they get back from vacation)

**Comment by quasiben** [comment]
Looking at this :)
