### ISSUE TITLE
Add quickstart for local usage

### ISSUE THREAD

**Issue by mrocklin** [jcrist/dask-gateway#50]
I may be missing something, but I can't find documentation on how to install this or get a basic setup running on my local machine.  I think that there used to be something like this (perhaps on a README), but I'm no longer able to find it.

**Comment by ericdill** [comment]
Did you see the demo subdir? That may be what youre looking for https://github.com/jcrist/dask-gateway/blob/master/demo/README.rst

**Comment by mrocklin** [comment]
Indeed.  A link from the docs to that file might be worthwhile.
Alternatively, maybe that file could enter the docs.

**Comment by jcrist** [comment]
The docs in general need an improvement. I'd like to expand demo setups to all the supported backends as well.
