### ISSUE TITLE
Better error messages for missing deps

### ISSUE THREAD

**Issue by quasiben** [jcrist/dask-gateway#58]
When trying to use a cluster manager with uninstalled external dependencies the error message is a bit too general.  For example, when trying to use `KubeClusterManager` I get

> The 'cluster_manager_class' trait of <dask_gateway_server.app.DaskGateway object at 0x7ff2ba00f198> instance must be a type, but 'dask_gateway_server.managers.kubernetes.KubeClusterManager' could not be imported

Installing the kubernetes python library (pip install kubernetes) resolves the issue

**Comment by jcrist** [comment]
Agreed. This is unfortunately how the default traitlets `Type` class works. Subclassing that trait type and overriding the loader to provide better errors would be one solution.
