### ISSUE TITLE
Dask submit command?

### ISSUE THREAD

**Issue by TomAugspurger** [jcrist/dask-gateway#89]
Maybe a silly question: would dask-gateway be a good home for a `dask submit` command, analogous to dask-yarn's https://yarn.dask.org/en/latest/submit.html#submitting-an-application?

**Comment by jcrist** [comment]
Not in the same way, there's not a clear place for the client to run. We could add a submit extension to the scheduler to take scripts and run them on the scheduler, but that could be done anywhere (the old `dask-remote` and `dask-submit` did this in a similar way - I don't think these ever got much use though).

What's your use case here?

**Comment by TomAugspurger** [comment]
Thanks.

> What's your use case here?

Thinking a bit about how to submit batch-style workflows to a jupyterhub deployment. Like "run this script training a model", that's not tied to the life of a notebook. Basically piggy backing on the auth stuff dask-gateway is doing with jupyterhub.

**Comment by jcrist** [comment]
I assume this is in the context of pangeo? I discussed a design (and prototyped part of it here: https://github.com/jcrist/papermillhub) for doing this with @rabernat and @danielballan at SciPy. I think tying things to dask is the wrong model, and we want to think about running notebooks in headless mode on the existing JupyterHub architecture. This work dropped off a bit due to getting busy with other things, but we discussed a clear design plan that I think would be a good way forward. I'd be happy to discuss this more elsewhere if people are interested.

**Comment by mrocklin** [comment]
I would also like to see submitting scripts to JupyterHub.  I've brought this up before and received negative response, but I think it would be good for others to chime in.

https://github.com/jupyterhub/jupyterhub/issues/2394

**Comment by jcrist** [comment]
I think this can easily be patched on as a separate service using the services API, and doesn't need to be part of jupyterhub core. The plan I outlined above would be:

- A JupyterHub service that manages a queue of notebook jobs to run per-user.
- Each job is run on a spawner instance (these could be reused, or each job could request a new spawner).
- The notebook server in the spawner is running a notebook extension (already prototyped in https://github.com/jcrist/papermillhub) that allows running a notebook headlessly, and returns the contents.

This uses the existing jupyterhub infrastructure to handle authentication and backend management (e.g. getting a container to run the job in), and can be done completely outside of JupyterHub proper. The design is currently specific to running notebooks in a papermill-esque manner, but could be extended to general scripts if desired.

**Comment by TomAugspurger** [comment]
Yeah, this primarily motivated by the Pangeo context. The "as a jupyter service" thing make sense.

So IIUC, there isn't too much overlap between what you layout in https://github.com/jcrist/dask-gateway/issues/89#issuecomment-530481475 and what dask-gateway is already doing (authentication, cluster config)?

**Comment by jcrist** [comment]
Yeah, what I'm picturing would be a separate project entirely.

**Comment by TomAugspurger** [comment]
Thanks. I'll let you know if I get bored and explore the service idea.
